# Generated by Django 3.0.6 on 2020-10-01 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
                ('schedule_date', models.DateField(default=datetime.datetime(2020, 10, 2, 15, 4, 36, 525952))),
                ('is_done', models.BooleanField(default=False)),
                ('days_overdue', models.IntegerField(default=0)),
            ],
        ),
    ]
