# Generated by Django 3.0.6 on 2020-10-01 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 2, 15, 6, 17, 795315)),
        ),
    ]
